### ISSUE TITLE
Segfault in BasicHashTable with hashtables >= 1.2.0.0

### ISSUE THREAD

**Issue by travitch** [gregorycollins/hashtables#24]
I ran into a segfault with the newer releases of hashtables under both ghc 7.6.3 and 7.8.4.  My workload looks up keys in the hash table, inserting them with some value if they are not already present.  The order is basically random.  Here is a test program:

```{.haskell}
{-# LANGUAGE ViewPatterns #-}
module Main ( main ) where

import qualified Data.HashTable.IO as IOH

import qualified Data.Time.Clock as C
import qualified System.Environment as E
import qualified System.Random as R
import Text.Printf ( printf )

main :: IO ()
main = do
  (read -> nActions) : args <- E.getArgs
  rgen <- case args of
    [] -> do
      now <- C.getCurrentTime
      let seed = fromIntegral ((floor (C.utctDayTime now)) :: Int)
      _ <- printf "Seed: %d\n" seed
      return $ R.mkStdGen seed
    seed : _ -> return $ R.mkStdGen (read seed)
  ht <- IOH.newSized 8192
  stress ht (take nActions (R.randoms rgen))
  return ()

stress :: IOH.BasicHashTable Int Int -> [Int] -> IO ()
stress _ [] = return ()
stress ht (val:rest) = do
  res <- IOH.lookup ht val
  case res of
    Nothing -> IOH.insert ht val val
    Just _ -> return ()
  stress ht rest
```

and a cabal file to build it

```
name:                ht-test
version:             0.1.0.0
synopsis:            hashtables stress test
license:             BSD3
license-file:        LICENSE
author:              Tristan Ravitch
maintainer:          tristan@nochair.net
category:            Data
build-type:          Simple
cabal-version:       >=1.10

executable ht-test
  main-is:             Main.hs
  build-depends:       base == 4.*,
                       random,
                       time,
--                       hashtables == 1.2.0.1
--                       hashtables == 1.2.0.0
                       hashtables < 1.2
  default-language:    Haskell2010
  ghc-options:         -Wall
```

The program takes two parameters: the number of (random) values to look up/insert and the seed to initialize the random number generator with.  I have two interesting inputs to report:

# Crash

`ht-test 100000 1862` causes a segfault with `hashtables >= 1.2`.  With 1.1, it acts as expected.  That is 100,000 elements starting with a seed of 1862.

# Infinite loop (or maybe just a huge slowdown?)

This is probably an infinite loop, and probably also just another manifestation of the same underlying problem as the segfault: `ht-test 1000000 12`  This completes in about 6 seconds with `hashtables < 1.2`.  I never saw it finish for 1.2+.  I did some profiling on my real application and it looked like execution was looping forever in `delete'.go` in the BasicHashTable code.

I'll try to look for some smaller test cases that trigger these issues.  Finding the larger ones was a bit easier.

**Comment by glguy** [comment]
As far as smaller test cases go:

```haskell
module Main ( main ) where

import Data.Foldable (for_)
import qualified Data.HashTable.IO as IOH 

main :: IO ()
main = do
  ht <- IOH.newSized 8192 :: IO (IOH.BasicHashTable Int ()) 
  for_ [1 ..] $ \val ->
    do print val 
       IOH.insert ht val ()
```

This code gets to `98318` on my computer and then just hangs.

**Comment by gregorycollins** [comment]
To help me narrow this down:

  - 64-bit or 32-bit?
  - what platform are you running on?

**Comment by travitch** [comment]
64 bit linux

**Comment by glguy** [comment]
I tested on 64-bit OS X 10.10.1 with GHC 7.8.4

**Comment by glguy** [comment]
With debugging input turned out we see that my code loops printing this repeatedly:
````
forwardSearch3 returned 32782 with sz=98317, b=32783
h0 was 32782
found he == h0 == 32782
go: fp=Slot {_slot = 9223372036854775807, _wasDeleted = 0} b=32783, wrap=False, he=32782, emptyMarker=0, deletedMarker=1
```

**Comment by gregorycollins** [comment]
This was an embarrassing oversight on my part. The test suite didn't trigger the obvious bug either. Please try 1.2.0.2.

**Comment by glguy** [comment]
Seems to work better for me!

Thanks for the fix.

**Comment by travitch** [comment]
Looks good to me too - it fixes my test case and larger application.  Thanks.
