### ISSUE TITLE
Orphan Monoid Instance

### ISSUE THREAD

**Issue by sheganinans** [gregorycollins/hashtables#28]
Hi! Would just like to mention that hashtables can form a monoid, it would be nice to not have this implemented as an orphan. Also I think that there might be a faster implementation, maybe someone else might be able to suggest something better?

```haskell
instance (HashTable h, Eq a, Hashable a, Monoid v) => Monoid (IO (h RealWorld a v)) where
 mempty = H.new
 mappend a b = do
  a' <- a
  b' <- b
  H.mapM_ (uncurry $ update a') b'
  return a'
 mconcat = foldl' mappend mempty

update h k w = do
 l <- H.lookup h k
 case l of
  Nothing -> H.insert h k mempty
  Just v -> H.insert h k $ v `mappend` w
```

**Comment by gregorycollins** [comment]
This is not really properly monoidal unfortunately, sorry, and would require overlapping instances.
