### ISSUE TITLE
Consider using hashabler instead of hashable?

### ISSUE THREAD

**Issue by jberryman** [gregorycollins/hashtables#30]
Would you be interested in merging changes that moved from `hashable` to my [`hashabler`](https://hackage.haskell.org/package/hashabler) project? [Here](http://brandon.si/code/announcing-hashabler-like-hashable/)'s a blog post I wrote that introduces an older version.

This would leave the API more or less unchanged but would
- allow the data structures here to be safely public facing, by using SipHash
- permit extending the API to make the choice of hash function user-configurable
- be generally less sketchy
- support consistent cross platform hashing, and in turn makes possible consistent serialization of these structures

The downsides might include:
- `hashable` may have greater backwards compatibility
- `hashable` is more widely used and users would need to redefine any custom data type instances for `hashabler`'s `Hashable`
- we don't yet support deriving instances with TH

The last two downsides will get mostly solved together when I define a TH deriving routine that's a drop-in replacement for `hashable`'s.

I'm not sure when I'd be able to get to a PR, but I wanted to float the idea first. Let me know if you're interested and would like more details about what that might look like. Also if this idea sounds appealing but you have changes you'd need to see made in `hashabler` first. Thanks!

**Comment by gregorycollins** [comment]
Unlikely, sorry. You would be better off trying to work with @tibbe to introduce the changes you want into hashable --- and if you can't convince him to do it, you're unlikely to be able to convince me either. To me it's more important that `hashtables` and `unordered-containers` match.
