### ISSUE TITLE
[perf.] CuckooHashTable vs BasicHashTable

### ISSUE THREAD

**Issue by kgadek** [gregorycollins/hashtables#39]
I stumbled upon [this SO thread](http://stackoverflow.com/q/3058529/547223). It's quite dated, so I wanted to test it on GHC 8.0.2.

First, I've used CuckooHashTable (code attached below) — as can be easily verified, I'm using `hashtables-1.2.1.0` there. The results on OSX are dissatisfying: ~4.4s for OCaml, ~16s for Haskell.

Then I've changed `CuckooHashTable` to `BasicHashTable` and automagically the Haskell got into ~4.4s range.

Docs state that:

> Randomized testing shows this implementation of cuckoo hashing to be slightly faster on insert and slightly slower on lookup than Data.Hashtable.ST.Basic, while being more space efficient by about a half-word per key-value mapping.

While `[1..10000000]` is certainly not randomized, the workload suggest that Cuckoo should be quicker than Basic but isn't. What's happening here?

Maybe the docs shall be slightly corrected?

```haskell
-- stack --resolver nightly-2017-02-08 ghc --package hashtables -- -O2 harrop_ghc.hs
import           Control.Monad
import qualified Data.HashTable.IO as H

type HashTable k v = H.CuckooHashTable k v

main = do
  m <- H.new :: IO (HashTable Int Int)
  forM_ [1..10000000] $ \n -> H.insert m n n
  v <- H.lookup m 100
  print v
```

```ocaml
(* ocamlopt -o harrop_ocaml harrop_ocaml.ml *)
let n = 10000000

let () =
  let m = Hashtbl.create n in
  for n=1 to n do
    Hashtbl.add m n n
  done;
  Printf.printf "%d\n%!" (Hashtbl.find m 100)
```

**Comment by gregorycollins** [comment]
Cuckoo needs a hash function that spreads the input around, otherwise it will collide a lot. `hash = id` for `Int`.

Re: your benchmark, you'll do better with "fromList", and "newSized" will do better than "new" because you won't waste time pointlessly resizing the table as it grows. Note that the ocaml version does the same (`Hashtbl.create n`).
