### ISSUE TITLE
Build error with GHC 8.4.1-alpha1

### ISSUE THREAD

**Issue by asr** [gregorycollins/hashtables#45]
GHC 8.4.1-alpha1 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2017-December/015235.html). While testing [Agda](https://github.com/agda/agda) with this version of GHC, I got the following error on hashtables (master branch):

```
$ cabal install
...
src/Data/HashTable/ST/Basic.hs:491:10: error:
    • No instance for (Semigroup Slot)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid Slot’
    |
491 | instance Monoid Slot where
    |          ^^^^^^^^^^^
Failed to install hashtables-1.2.2.1
```

Blocking https://github.com/agda/agda/issues/2878.

**Comment by asr** [comment]
Note that this error is reported as a warning in GHC 8.0.2/8.2.2 using the `-Wsemigroup` flag:

```
$ cabal install --force-reinstalls --ghc-options='-Wsemigroup -Werror'

So, fixing this warning on GHC 8.0.2/8.2.2 fix the error on GHC 8.4.1-alpha1.

**Comment by asr** [comment]
For knowing the warnings in GHC 8.0.2/8.2.2, I realised it's better to use the `-Wcompat` flag:

```
$ cabal install --force-reinstalls --ghc-options='-Wcompat -Werror'
```

**Comment by DanBurton** [comment]
Bump. ghc-8.4.1 is out now; same issue.

**Comment by simonmichael** [comment]
Two PRs have been pending for a while: #46, #47. @gregorycollins, any chance you could merge and ship a quick release ?

**Comment by mgmeier** [comment]
`hashtables` conforms to the SMP as of release `1.2.3.0`, closing this issue now.
