### ISSUE TITLE
1.2.3.0 breaks ghc pre 7.10

### ISSUE THREAD

**Issue by cohomology** [gregorycollins/hashtables#48]
Can it be, that 1.2.3.0 silently breaks compatibility with ghc < 7.10, e.g. without applicative => monad proposal?

gtk2hs has no version constraint on hastables and I just run into by building svgcairo, see [here](https://travis-ci.org/gtk2hs/svgcairo/jobs/363170754).

That might be a good thing after all ...

**Comment by mgmeier** [comment]
fixed by #50
