### ISSUE TITLE
Why is performance a third of hash tables in other languages?

### ISSUE THREAD

**Issue by TomMD** [gregorycollins/hashtables#49]
Some years ago I note HashTables based solutions in Haskell didn't compare well, performance wise, with the same solution in Python.  For example, a trivial insert of millions of elements:

```
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
import Data.HashTable.IO as H
import qualified Data.ByteString as BS
import Data.Hashable

newtype Bad = B { unB :: Int }  deriving (Show, Enum, Ord, Eq)
instance Hashable Bad where
    hash (B i) = i
    hashWithSalt _ (B i) = i

main ::  IO ()
main = do
    ht <- H.new :: IO (H.BasicHashTable Bad BS.ByteString)
    let go (B 63000001) = pure ()
        go n = H.insert ht n BS.empty >> go (B $ unB n + 1)
    go (B 1)
```

In the above we're just inserting the pairs `[ (i, empty) | i <- [1 .. 63000000] ]`

Notice I've made the "hash" match python's integer hash (mostly, ignoring what they do with negatives) though this didn't have a meaninful performance impact.

The performance difference between this snippet and the matching python is about 3x (30 seconds for Haskell with ghc 8.4.1 `-O2 -fllvm -optl-march=native`, 8 or 10 seconds for python or pypy).  Has there been an exploration on this front? Is this mostly an issue with creating (and collecting) intermediate values such as `HashTable_`?

**Comment by unhammer** [comment]
That looks pretty nice @klapaucius – it also seems faster than `HashMap` in my testing. Hope we get to see it with a non-internal module on Hackage some day soon :)

**Comment by swamp-agr** [comment]
@unhammer please find release on hackage: https://hackage.haskell.org/package/vector-hashtables

**Comment by gregorycollins** [comment]
Regarding the original comment -- inserting sequential keys is worst-case for linear probing hash tables which is why it's recommended to use a good hash function that doesn't cluster keys around hash values
