### ISSUE TITLE
Please add a method to update a value in place

### ISSUE THREAD

**Issue by peti** [gregorycollins/hashtables#6]
I would like to update a value stored in a hashtable. The `unordered-containers` package provides methods like `insertWith` to do this, but the hashtable package unfortunately doesn't. The only way to update a value in place seems to be to do a lookup followed by an insert, but this strikes me as unnecessarily inefficient. Or am I missing something terribly obvious?

**Comment by ppetr** [comment]
+1, I'm missing a way how to get the old value overwritten by insert without an additional lookup. The suggested `updateEntry` sounds like an ideal solution.

Or perhaps a lens-like generalization:
```haskell
updateEntry :: (Eq k, Hashable k, Traversable f)
            => h s k v -> k -> (Maybe v -> f (Maybe v)) -> ST s (f ())
```

**Comment by FranklinChen** [comment]
It would be really great to have an update-in-place. I have verified that when I changed my code using immutable hashtables (from `unordered-containers`) to use this mutable API, having to look up and then reinsert basically doubled the time, and so I went back to the immutable for performance!

**Comment by gregorycollins** [comment]
@ppetr re: traversable, in a library like this we're going to stick with the monomorphic :)

I also propose "mutate" as the function name. "alter" would work also.
Enough people want this, but hashtables is number 3 in my project queue (at best) right now. I don't have time to work on this issue but here is broadly what is needed, in this order:

  - add mutate to the typeclass
  - write failing unit tests for mutate
  - implement mutate for the three hashtable implementations, tests go green (and coverage 100%). Separate CLs would be preferred for each (and easier to review).

I've done the first two items (adding mutate to typeclass and writing a failing unit test), but I don't have time to work on it further right now. If you want to send pull requests please send them to the "mutate" branch I just uploaded to github.

**Comment by jamesdbrock** [comment]
I'm trying out the *mutate* branch #26, and for my case the values stored in the hashtable are `(Ptr Int)`s. I would like to be able to dereference and mutate the pointees during the hashtable mutation.

Perhaps the mutate handler function should be an `ST` monadic function? Since the mutation is in the `ST` context, it should be simple to pass that context to the handler, and it makes the handler general enough to handle my case.

```
mutate :: (Eq k, Hashable k) => h s k v -> k -> (Maybe v -> ST s (Maybe v, a)) -> ST s a
```

**Comment by jamesdbrock** [comment]
I implemented `mutate` in the `ST` context and pushed it to the __mutate-st__ branch of my clone, if anyone's curious.

https://github.com/jamesdbrock/hashtables/tree/mutate-st

(It didn't give me the performance improvement over `lookup` + `insert` which I was hoping for, though.)
