### ISSUE TITLE
Flag portable does not work

### ISSUE THREAD

**Issue by Bodigrim** [gregorycollins/hashtables#88]
```
$ cabal get hashtables-1.4.0 && cd hashtables-1.4.0 && cabal build -w ghc-9.10 -fportable
Unpacking to hashtables-1.4.0/
Resolving dependencies...
Build profile: -w ghc-9.10.1 -O1
In order, the following will be built (use -v for more details):
 - hashtables-1.4.0 (lib) (first run)
 - hashtables-1.4.0 (test:testsuite) (first run)
Configuring library for hashtables-1.4.0...
Configuring test suite 'testsuite' for hashtables-1.4.0...
Preprocessing library for hashtables-1.4.0...
Building library for hashtables-1.4.0...
Preprocessing test suite 'testsuite' for hashtables-1.4.0...
Building test suite 'testsuite' for hashtables-1.4.0...
[ 1 of 12] Compiling Data.HashTable.Class
[ 1 of 14] Compiling Data.HashTable.Class
[ 2 of 12] Compiling Data.HashTable.Internal.Array
[ 2 of 14] Compiling Data.HashTable.Internal.Array
[ 3 of 12] Compiling Data.HashTable.Internal.IntArray
[ 3 of 14] Compiling Data.HashTable.Internal.IntArray
[ 4 of 12] Compiling Data.HashTable.Internal.UnsafeTricks
[ 4 of 14] Compiling Data.HashTable.Internal.UnsafeTricks
[ 5 of 12] Compiling Data.HashTable.Internal.Linear.Bucket
[ 5 of 14] Compiling Data.HashTable.Internal.Linear.Bucket
[ 6 of 12] Compiling Data.HashTable.Internal.Utils
[ 6 of 14] Compiling Data.HashTable.Internal.Utils
[ 7 of 12] Compiling Data.HashTable.Internal.CheapPseudoRandomBitStream
[ 7 of 14] Compiling Data.HashTable.Internal.CheapPseudoRandomBitStream
[ 8 of 12] Compiling Data.HashTable.Internal.CacheLine
src/Data/HashTable/Internal/CacheLine.hs:254:30: error: [GHC-83865]
    • Couldn't match expected type ‘Int#’ with actual type ‘Int8#’
    • In the first argument of ‘int2Word#’, namely ‘pos8#’
      In the expression: int2Word# pos8#
      In an equation for ‘posw#’: !posw# = int2Word# pos8#
    |
254 |     !posw#       = int2Word# pos8#
    |                              ^^^^^
<skipped>
```

**Comment by erikd** [comment]
Kind of curious what you are using the `portable` flag for.

**Comment by Bodigrim** [comment]
See https://www.reddit.com/r/haskell/comments/1gzg3tx/failed_to_build_hashtables_on_wasm32wasighc/ for context.

I think the original poster uses `-fportable` as a hack to get `hashtables` working on 32-bit arch; it would be nice to test and fix it if necessary. If you do not have a local 32-bit machine, https://github.com/haskell/text/blob/master/.github/workflows/i386.yml can be used as a template for CI job on `i386`.

**Comment by erikd** [comment]
Oh no. Supporting 32 bit is such a huge pain in the neck. It breaks horrible for most new GHC releases. I put a huge amount of effort into fixing `wide-word` many releases ago, only to have it break really horribly on the next major release.

**Comment by erikd** [comment]
Fixing `-fportable` on `x86-64` should not be too hard, but making sure it also works on 32 bit is probably going to be painful and I would be surprised if it doesn't break for the next major GHC release.

**Comment by Bodigrim** [comment]
Well, WASM and JS are 32-bit targets and supporting them is not without a merit. But if you decide otherwise, I guess `if arch(i386) || arch(arm) || arch(wasm) || arch(js) buildable: False` would be helpful for users so that at least Cabal rejects a build plan.

**Comment by erikd** [comment]
Is there any particular 32 bit WASM GHC version I should be supporting?

**Comment by angerman** [comment]
unsized types bite again :(

**Comment by erikd** [comment]
Eeek, the compile error @Bodigrim posted is just the first of about 10, and that particular error does not occur with `ghc-8.10`.
